GENERAL:
  task: train  # train, test
  manual_seed: 123
  model_dir: model/pointgroup/pointgroup.py
  dataset_dir: data/OCID.py

DATA:
  data_root: /raid/chrisxie/OCID-dataset/
  dataset: OCID

  classes: 3
  ignore_label: -100

  input_channel: 3
  scale: 250   # voxel_size = 1 / scale, scale 50 = 2cm, scale 250 = 4mm
  batch_size: 4
  full_scale: [512, 2048]  # Original values were [128, 512]. Multiplied by 4
  max_npoint: 350000  # Each image has a point cloud of 307200 = 480*640
  mode: 4 # 4=mean

  subsample_factor: 1
  far_plane: 3.  # Anything above this depth is not considered
  near_plane: 0.25  # Anything closer tan this depth is not considered (TOD data subtlety issue... this will blow up v2p_map)

STRUCTURE:
  model_name: pointgroup
  m: 16 # 16 or 32
  block_residual: True
  block_reps: 2

  use_coords: True

  score_scale: 250 # the minimal voxel size is 4mm. This is 5x smaller than PointGroup (on ScanNet), which uses 2cm
  score_fullscale: 70 # Original value (ScanNet) was 14, 5x means 70.
  score_mode: 4 # mean

GROUP:
  ### point grouping
  cluster_radius: 0.006  # Original value was 0.03. Divided by 5
  cluster_meanActive: 50
  cluster_shift_meanActive: 300
  cluster_npoint_thre: 50

  prepare_iters: 100000  # 1/3 of the training

TEST:

  pretrain_path: /home/chrisxie/local_installations/PointGroup/exp/TOD/pointgroup/pointgroup_TOD/001/pointgroup_TOD-000000005.pth
  pretrain_module: ['input_conv', 'unet', 'output_layer', 'linear', 'offset', 'offset_linear',
                    'score_unet', 'score_outputlayer', 'score_linear']
  fix_module: []


  split: val
  test_epoch: 5
  test_workers: 16
  test_seed: 567

  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 500

  eval: True
  save_semantic: False
  save_pt_offsets: False
  save_instance: False

